'\" t
.\"     Title: pybit-watcher
.\"    Author: [see the "Author" section]
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 02/15/2013
.\"    Manual: pybit-watcher
.\"    Source: November 2012
.\"  Language: English
.\"
.TH "PYBIT\-WATCHER" "1" "02/15/2013" "November 2012" "pybit\-watcher"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
pybit-watcher \- watches incoming directories for reprepro
.SH "SYNOPSIS"
.HP \w'\fBpybit\-watcher\fR\ 'u
\fBpybit\-watcher\fR [\fIoptions\fR]
.SH "DESCRIPTION"
.PP
pybit\-watcher monitors a nominated directory for Debian package uploads (*\&.changes) and then runs a specified incoming rule on the configured reprepro repository\&.
.SH "OPTIONS"
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
show this help message and exit
.RE
.PP
\fB\-\-conf_file\fR=\fIPYBIT_WATCHER_CONF_FILE\fR
.RS 4
Config file to read settings from, defaults to watcher\&.conf which will be read from configs/watcher and /etc/pybit/watcher in turn\&.
.RE
.PP
\fB\-v\fR
.RS 4
Turn on verbose messages\&.
.RE
.PP
\fB\-d\fR
.RS 4
Daemonise with output going to /var/log/pybit\-watcher
.RE
.SH "DAEMON CONFIGURATION"
.PP
pybit\-watcher needs to be configured before it will run and process uploads\&. The configuration file is in JSON format, ordering is not important\&.
.PP
\fIrepobase\fR
\- top level directory of the
reprepro
repository, i\&.e\&. where
reprepro
can find the
\&./conf/distributions
file\&.
.PP
\fIpath\fR
\- directory used for uploads, must be writeable by whichever user(s) will be able to upload\&.
.PP
\fIdryrun\fR
\- if set to true, commands are printed to the console instead of being executed\&. Default: true
.PP
\fIrule\fR
\- the
reprepro
incoming rule to call with this watcher\&. Only one incoming rule can be used\&.
.PP
\fIsleeptime\fR
\- the time allowed after the watcher is notified that a \&.changes file has been written to allow for the upload tool to change permissions or other management tasks\&. Default: 3 seconds\&.
.PP
\fIconfigured\fR
\- Set to true once the other settings are correct for your installation\&. Default is false\&.
.SH "AUTHOR"
.PP
This manual page was written by Neil Williams
codehelp@debian\&.org
